### ISSUE TITLE
torch模型在线推理使用preload_app=True？

### ISSUE THREAD

**Issue by ucas010** [aliyun/algorithm-base#3]
哈喽，大佬，算法模型部署的config.py（gunicorn使用）preload_app=True么？
这个参数为False后该work如果响应不了还会重启么？
线程数应该设置为多少呢？单个请求约1s，timeout设置多少合适呢？
感谢

**Comment by cactusgame** [comment]
> 哈喽，大佬，算法模型部署的config.py（gunicorn使用）preload_app=True么？ 

要看torch的版本和你使用到的功能，如果对性能要求不高，preload_app = False 更保险一些。

> 线程数应该设置为多少呢？单个请求约1s，timeout设置多少合适呢？

根据你业务的实际情况，压测来决定参数吧，这个不是框架该考虑的问题

**Comment by ucas010** [comment]
大佬，
torch 1.13
并发请求数80，worker应该设置多少呢？
worker_class = "sync" 和"gevent"这两个哪个好啊？模型响应较慢时。

**Comment by ucas010** [comment]
当进程起来后，我采用kill -9杀死pid，发现ps下会新增进程，这是咋回事啊？能不能不新增进程啊？
