### ISSUE TITLE
运行报错：AttributeError: module 'numpy' has no attribute 'bool'

### ISSUE THREAD

**Issue by xiuxiuing** [aliyun/algorithm-base#4]
##### 报错原因

在`numpy 1.24.0`及之后的版本，已经弃用的`np.bool`  `np.int`等已经完全删除。最后包含`np.bool`的版本是`numpy 1.23.5`

##### 解决方案

目前的方案是降级numpy

```shell
pip uninstall numpy
pip install numpy==1.23.1
```

后续会考虑做版本兼容吗？

**Comment by cactusgame** [comment]
> ##### 报错原因
> 在`numpy 1.24.0`及之后的版本，已经弃用的`np.bool` `np.int`等已经完全删除。最后包含`np.bool`的版本是`numpy 1.23.5`
> 
> ##### 解决方案
> 目前的方案是降级numpy
> 
> ```shell
> pip uninstall numpy
> pip install numpy==1.23.1
> ```
> 
> 后续会考虑做版本兼容吗？

短期内没有升级计划
